# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa082778b80b6e8bfb5dc5fc4378b6f6770cbf67b053e88209e495bcb5401e606c04483726ba4c76ab7f3edf0a251d692ba58b1e45d8026df3007ce4838075d6

test:
  secret_key_base: 434ec8b52243ed253bc9f852e8867ba69affbd6b487b4b5ea21006e8098648e69c263d6453417bf620899d2bc7f72f35b565a5155911fb5bc70903b18b066950

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
